# Use a base image with Java installed
FROM openjdk:11-jre-slim
# Copy the application JAR file into the container
ADD target/Employee-Service-0.0.1-SNAPSHOT.jar .
EXPOSE 8082
# Specify the command to run your application
CMD ["java", "-jar", "Employee-Service-0.0.1-SNAPSHOT.jar"]
