version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: emp
    ports:
      - "5430:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - micro
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/emp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - micro

volumes:
  postgres-data:

networks:
  micro:
    external: true
    driver: bridge